### ISSUE TITLE
Get Term Image code

### ISSUE THREAD

**Issue by JoelEadeDesign** [stuttter/wp-term-images#1]
Hi John,

I'm using this plugin with WordPress 4.4-beta1. I've used the code snippet from the readme and found it just returns the meta_value for the term_id. Seeing as the code is echoing the img element I imagine it should return the image URL. I found that the below worked for my purposes:

```
$image = get_term_meta( 452, 'image', true );
    if ( ! empty( $image ) ) {
        echo '<img src="' . esc_url( wp_get_attachment_image_url( $image, 'full' ) ) . '" />';
}
```

I'm very much a PHP n00b, so if this isn't relevant please ignore this issue.

Cheers,

Joel

**Comment by johnbillion** [comment]
I'm not the author of this plugin, but the above code is correct. This is the intended and correct way to output the term image. :+1:

**Comment by JoelEadeDesign** [comment]
Cool, thanks John. I use User Switching and Query Monitor all the time, so your word is as good as JJJ's for me :) :+1:
