### ISSUE TITLE
Quick Edit Replaces Image Meta Value

### ISSUE THREAD

**Issue by daronspence** [stuttter/wp-term-images#2]
To reproduce:
- Add a new term w/ an image. 
- Quick edit and save the term
- Check meta value for term (you can inspect the `admin-ajax.php` network request
- ???
- Profit

The issue stems from `/assets/js/term-image.js` on `Line 113`. The image URL is being inserted instead of the image's attachment ID.

It looks like removing that line fixes it. Since the image is already set, the value doesn't need to be overridden every time someone clicks the quick edit button. I could have overlooked something though.

Cheers :tada:

**Comment by JJJ** [comment]
Hi @Daronspence!

Thanks for this report. I'm about to fix it, in a bit of a different way.

The reason that line of JS exists, is to update the quick edit row when, say, you choose to quickly edit two or three different rows back-to-back.

I wouldn't have noticed this issue without this report, so I appreciate you letting me know!

**Comment by daronspence** [comment]
Awesome. Thanks! Just about to use this on another client project with lots of meta terms so the inline editing is handy.

**Comment by JJJ** [comment]
Fixed in 0.3.1, about to be tagged. Thanks again for your help.
