### ISSUE TITLE
Image preview size is tiny

### ISSUE THREAD

**Issue by benhuson** [stuttter/wp-term-images#3]
Hi,

Love your new suite of Term Meta plugins.

Was just trying out this term image plugin.  
Works well and is nice and clean, but I found the preview image in the admin list view feels teeny tiny at 25 x 25 px - it doesn't feel big enough to be a preview, just lets you know there is an image assigned.

Any reason you don't use a larger preview like the Media list view which is 60 x 60 px?  
(I could obvious hook in and override the styling, just wondering if the default is too small)

As a sidenote, I took over management of the [Taxonomy Images](https://github.com/benhuson/Taxonomy-Images) plugin which used to be managed by Michael Fields but needed some updating for recent versions of WordPress - was still using old media modal. I've not yet moved it over to use term meta but I'd like to make that transition including migration of old data etc. If I were to do that, what are your thoughts on storing the image ID using the same meta key as your plugin so that the 2 plugins could be interchangeable - good idea or bad idea? Certainly would't want to do that without your blessing :wink: 

Ben

**Comment by JJJ** [comment]
Hey @benhuson! Thanks for reaching out, and congrats on inheriting that plugin, and all the joys that go with that responsibility. :)

Regarding the image size, my goal is always to hug as close to the existing experience as possible, and not assume ownership over pretty much anything. For this, it meant not assuming it was okay to increase the height of some table rows that may have thumbnails, and not others that do not. With that in mind, I think it's passable to have a visual representation of the image without needing to emphasize it, if that makes sense? But, as with everything, I love being wrong and am totally open to suggestion and education here.

I think it's a great idea to share meta keys, especially for simple things like this that realistically should never need to change. If we ever do need to change the value, then it becomes a nasty mess and breaks stuff, so I really appreciate you reaching out to get me thinking about it.

**Comment by JJJ** [comment]
Gonna close this, for now. If anyone wants to run with these thoughts, please do!
