### ISSUE TITLE
Choose Image button not working on edit term screen.

### ISSUE THREAD

**Issue by lukemcdonald** [stuttter/wp-term-images#9]
When creating a new term (edit-tags.php), the "Choose Image" button works and the Media Modal displays.

When editing a single term (term.php), the "Choose Image" button does not launch the Media Modal.

**WP**: v4.5.3
**WP Term Images**: 0.3.0

**Comment by JJJ** [comment]
Oh no. I'll look into this and report back.

(I really thought I tested all of these conditions, but clearly missed this one.)

**Comment by JJJ** [comment]
Fixed in 39472f62dafa7fcdd0869873ebb8c705f14ecd09.
